SELECT A.ID "ID", A.TITLE "TITLE", COUNT(*) "COUNT" 
FROM
(SELECT C.ID, C.TITLE FROM YOUTUBES C) A
JOIN
(SELECT D.YOUTUBE_ID FROM COMMENTS D) B
on LOWER(A.ID) = LOWER(B.YOUTUBE_ID)
GROUP BY A.ID, A.TITLE
HAVING COUNT(*) > 0 
ORDER BY COUNT(*) DESC, LOWER(A.ID)